# Generated by Django 4.2.10 on 2026-07-06 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('misago_users', '0034_user_require_content_approval_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_name', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='style', to='misago_users.group')),
            ],
        ),
    ]
