# Generated by Django 4.2.10 on 2026-04-29 21:03

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("misago_edits", "0002_move_data"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="postedit",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["plugin_data"], name="misago_edit_plugin__7827ec_gin"
            ),
        ),
    ]
